// Cut a release: stamp the CHANGELOG, bump the version, commit, tag.
//
// The manual sequence this replaces is four edits that all have to agree with each other, and
// every way they can disagree fails LATE — after the tag is public:
//   - `release.yml` refuses to build when the tag disagrees with `package.json`. A forgotten bump
//     means a red run on a tag that already exists, and the fix is deleting a pushed tag.
//   - It lifts the Release notes out of the `## [x.y.z]` CHANGELOG section, and a MISSING section
//     is only a warning: the Release still publishes, just with autogenerated notes instead of the
//     ones written in the repo. Nothing goes red; the notes are quietly the wrong ones.
//   - CI runs typecheck/lint/test/build only once the tag is pushed. This script runs the same
//     four gates first, so a failure happens while the tag is still nothing but a local idea.
//
// What it does NOT do is push. Pushing the tag is the irreversible half — that is what makes the
// Release public — so it stays an explicit second step unless you ask for `--push`.
//
// Usage:
//   npm run release -- 0.5.0                stamp + bump + commit + tag, all local
//   npm run release -- 0.5.0 --push         … and push the branch and the tag
//   npm run release -- 0.5.0 -m "why"       commit body (previous release commits carry one)
//   npm run release -- 0.5.0 --no-verify    skip the local gates
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const run = (cmd, args, { inherit = false } = {}) =>
  execFileSync(cmd, args, { cwd: root, encoding: 'utf8', stdio: inherit ? 'inherit' : 'pipe' });
const die = (msg) => {
  console.error(`release: ${msg}`);
  process.exit(1);
};

// ---- arguments ----
let version = null;
let push = false;
let verify = true;
let body = '';
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--push') push = true;
  else if (a === '--no-verify') verify = false;
  else if (a === '-m' || a === '--message') body = argv[++i] ?? '';
  else if (a.startsWith('-')) die(`unknown flag ${a}`);
  else if (version) die('give exactly one version');
  else version = a.replace(/^v/, '');
}
if (!version) die('usage: npm run release -- <version> [--push] [--no-verify] [-m "body"]');
if (!/^\d+\.\d+\.\d+$/.test(version)) die(`not a release version: ${version}`);

// ---- guards ----
const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const triple = (v) => v.split('.').map(Number);
const isNewer = (a, b) => {
  const [x, y, z] = triple(a);
  const [p, q, r] = triple(b);
  return x !== p ? x > p : y !== q ? y > q : z > r;
};
if (!isNewer(version, pkg.version)) die(`${version} is not newer than the current ${pkg.version}`);

// A dirty tree would mean the four gates below test something other than what gets tagged.
if (run('git', ['status', '--porcelain']).trim()) die('working tree is dirty — commit or stash first');
if (run('git', ['tag', '--list', `v${version}`]).trim()) die(`tag v${version} already exists`);

// The Unreleased section becomes this version's section, so it has to have something in it.
const clPath = path.join(root, 'CHANGELOG.md');
const before = fs.readFileSync(clPath, 'utf8');
const header = '## [Unreleased]\n\n';
const at = before.indexOf(header);
if (at < 0) die('CHANGELOG.md has no "## [Unreleased]" section');
const rest = before.slice(at + header.length);
const next = rest.search(/^## \[/m);
if (!(next < 0 ? rest : rest.slice(0, next)).trim()) {
  die('the Unreleased section is empty — nothing to release');
}

// ---- gates: the same four release.yml runs, but before the tag exists ----
if (verify) {
  for (const step of ['typecheck', 'lint', 'test', 'build']) {
    console.log(`release: npm run ${step}`);
    try {
      run('npm', ['run', step], { inherit: true });
    } catch {
      die(`npm run ${step} failed — nothing was changed`);
    }
  }
}

// ---- stamp, bump, commit, tag ----
// Everything below edits files. If any of it throws, say what is left on disk: an aborted release
// that silently leaves a bumped package.json behind is worse than one that fails loudly.
const now = new Date();
const date = [
  now.getFullYear(),
  String(now.getMonth() + 1).padStart(2, '0'),
  String(now.getDate()).padStart(2, '0'),
].join('-');
const files = ['CHANGELOG.md', 'package.json', 'package-lock.json'];
try {
  // `## [Unreleased]` stays where it is, empty, and this version's header goes under it — the
  // shape every previous release commit produced.
  fs.writeFileSync(clPath, before.slice(0, at + header.length) + `## [${version}] - ${date}\n\n` + rest);
  run('npm', ['version', version, '--no-git-tag-version']); // package.json + package-lock.json
  run('git', ['commit', '-m', body ? `chore(release): ${version}\n\n${body}\n` : `chore(release): ${version}\n`, '--', ...files]);
  run('git', ['tag', '-a', `v${version}`, '-m', `v${version}`]);
} catch (err) {
  console.error(String(err.stderr || err.message || err).trim());
  die(`failed partway through. Check \`git status\`; \`git checkout -- ${files.join(' ')}\` undoes the edits.`);
}

const branch = run('git', ['rev-parse', '--abbrev-ref', 'HEAD']).trim();
console.log(`release: ${pkg.version} → ${version} committed and tagged v${version} on ${branch}`);
if (push) {
  run('git', ['push', 'origin', branch, `v${version}`], { inherit: true });
  console.log('release: pushed — release.yml will run the gates again and publish the Release');
} else {
  console.log(`release: not pushed. To publish:\n\n    git push origin ${branch} v${version}\n`);
}
